name: 7x24 Minecraft Entity Bot (Mineflayer)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Mineflayer
        run: |
          npm install --omit=dev

      - name: Run Mineflayer KeepAlive Bot
        run: |
          node bot.js
